repository_type: pipeline

nf_core_version: 3.3.2

lint:
  files_unchanged:
    - .prettierignore
    - LICENSE
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-nf-pooled-cellpainting_logo_light.png
    - docs/images/nf-core-nf-pooled-cellpainting_logo_light.png
    - docs/images/nf-core-nf-pooled-cellpainting_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
    - .prettierignore
    - .prettierignore
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  multiqc_config:
    - report_comment
  files_exist:
    - LICENSE
    - CODE_OF_CONDUCT.md
    - assets/nf-core-nf-pooled-cellpainting_logo_light.png
    - docs/images/nf-core-nf-pooled-cellpainting_logo_light.png
    - docs/images/nf-core-nf-pooled-cellpainting_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
  readme:
    - nextflow_badge
    - nfcore_template_badge

template:
  org: seqera-services
  name: nf-pooled-cellpainting
  description: A Nextflow pipeline for analysing optical pooled screens (OPS) data.
  author: Florian Wuennemann, Ken Brewer, Erin Weissbart, Shantanu Singh, and Seqera Services
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features:
    - github_badges
    - license
    - igenomes
    - fastqc
    - gpu
    - gitpod
    - vscode
    - rocrate
    - email
    - adaptivecard
    - slackreport
  is_nfcore: false
